trigger:
- '*'

pool:
  name: 'Default'

variables:
  solution: '**/FiapFase1.sln'
  webProject: 'FiapFase1.Interface/FiapFase1.Interface.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Preparando pacotes NuGet'

- task: NuGetCommand@2
  displayName: 'Restaurando pacotes NuGet'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Web Project'
  inputs:
    solution: '$(webProject)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Executando Testes do Web'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publicando Artefatos do Web'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
    ArtifactName: 'ArtefatoWeb'

- task: AzureRmWebAppDeployment@4
  displayName: 'Publicar Web no Azure App Service'
  inputs:
    azureSubscription: 'Assinatura do Azure 1 (db5db7fd-149c-4ccb-9268-d9e4c37ab9c0)'
    appType: 'webApp'
    WebAppName: 'techchallenge-web'
    package: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
