// <auto-generated />
using FiapFase1.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapFase1.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240810182900_AddDDDAndUpdateContato_2")]
    partial class AddDDDAndUpdateContato_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapFase1.Domain.Entities.Models.Contato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DDDId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Nome");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("NrTelefone");

                    b.HasKey("Id");

                    b.HasIndex("DDDId");

                    b.ToTable("Contato", (string)null);
                });

            modelBuilder.Entity("FiapFase1.Domain.Entities.Models.DDD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("NrDDD")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("DDD");
                });

            modelBuilder.Entity("FiapFase1.Domain.Entities.Models.Contato", b =>
                {
                    b.HasOne("FiapFase1.Domain.Entities.Models.DDD", "DDD")
                        .WithMany("Contatos")
                        .HasForeignKey("DDDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DDD");
                });

            modelBuilder.Entity("FiapFase1.Domain.Entities.Models.DDD", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
