  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Isso é necessário para solicitar o JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api-app  # Alterado para corresponder ao nome do artefato carregado
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A96BEBA3245C475DA6A93B013A432322 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_915E34B79C064C94B4A3392D41CAB592 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0249C27C44F8401BB737B6004FDC8DF8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'techchallenge-api'
          slot-name: 'Production'
          resource-group-name: 'fiap-api'
